---
openapi: 3.0.0
info:
  title: Swagger Petstore
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/vaniliacahya/E-Store/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://rubahmerah.site/
  description: Ini adalah link untuk deployment
tags:
- name: authentication
  description: Layanan untuk authentikasi user
- name: users
  description: Layanan yang mengorganisir data user
- name: admins
  description: Layanan yang mengorganisir product by admin
- name: products
  description: Layanan yang mengorganisir data product
- name: orders
  description: Layanan yang mengorganisir data order
paths:
  /login:
    post:
      tags:
      - authentication
      summary: ini fitur login
      description: Menambahkan data user baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelUser'
            example:
              email: vanili@vanili
              password: vanili123
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 200
                message: Login success
                token: $3gjk2UHkndlAubdDiHOjnD238Dijk
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 400
                message: Wrong username or password
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
  /users:
    get:
      tags:
      - users
      summary: ini fitur lihat profile user dan my history order
      description: Tampilkan data user yang login
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                id: 1
                name: vanilia
                email: vanili@vanili
                address: jalan simpang titan VI L34
                phone: 812496.0
                data:
                - order: 1
                  total: 500000
                  created_at: 2022-09-11T12:40:00.000+0000
                - order: 2
                  total: 700000
                  created_at: 2022-09-11T12:40:00.000+0000
                code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    put:
      tags:
      - users
      summary: ini fitur update data user
      description: Update data user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelUser'
            example:
              nama: vanilicay
              email: vanili@be10
              address: jalan simpang titan
              phone: 8129999.0
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 200
                message: Success update data
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 400
                message: Wrong Input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    post:
      tags:
      - users
      summary: ini fitur register
      description: Menambahkan data user baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelUser'
            example:
              nama: vanila
              email: vanila@alterra.id
              password: vanila123
              address: jalan jalan
              phone: 8123455.0
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 200
                message: Register success
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelUser'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
    delete:
      tags:
      - users
      summary: ini fitur hapus data user
      description: Hapus data user sesuai id
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: '{"code":200,"message":"Success delete data"}'
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
  /admins:
    get:
      tags:
      - admins
      summary: ini fitur lihat semua data barang by admin
      description: Menampilkan seluruh data barang
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelAdmin'
              example:
              - productid: 1
                productname: Black T-Shirt
                stock: 3
                price: 700000
              - productid: 2
                productname: White T-Shirt
                stock: 3
                price: 700000
              - code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    put:
      tags:
      - admins
      summary: ini fitur update barang
      description: Update data barang sesuai id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelAdmin'
            example:
              productid: 1
              productname: Black T-Shirt
              stock: 4
              price: 500000
              foto: foto.jpg
        required: true
      responses:
        "200":
          description: Success update admin data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelAdmin'
              example:
                code: 200
                message: Success update post
        "400":
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelAdmin'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    post:
      tags:
      - admins
      summary: ini fitur tambah barang
      description: Menambahkan barang baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelAdmin'
            example:
              productid: 1
              productname: Black T-Shirt
              stock: 4
              price: 500000
              foto: foto.jpg
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelAdmin'
              example:
                code: 200
                message: Success creating a post
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelAdmin'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
    delete:
      tags:
      - admins
      summary: ini fitur hapus product
      description: Hapus data user sesuai id
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
              example: '{"code":200,"message":"Success delete post"}'
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
  /admins/history:
    get:
      tags:
      - admins
      summary: ini fitur lihat semua history order by admin
      description: Menampilkan seluruh data barang
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelUser_order'
              example:
              - orderid: 1
                total: 500000
                created_at: 2022-09-11T12:40:00.000+0000
              - orderid: 2
                total: 700000
                created_at: 2022-09-11T12:40:00.000+0000
              - code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
  /products:
    get:
      tags:
      - products
      summary: ini fitur lihat all product untuk user
      description: Menampilkan seluruh all histroy order
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelAdmin'
              example:
              - productid: 1
                productname: Black T-Shirt
                price: 500000
                photo: tshirtblack1.jpg
              - productid: 2
                productname: Yellow T-Shirt
                price: 500000
                photo: tshirtyellow1.jpg
              - code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
  /orders:
    post:
      tags:
      - orders
      summary: ini fitur tambah order
      description: Menambahkan order baru
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModelOrder'
            example:
              orderid: 1
              productid: 1
              qty: 1
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelOrder'
              example:
                code: 200
                message: Success creating a order
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelOrder'
              example:
                code: 400
                message: Wrong input
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
  /orders/idorder:
    get:
      tags:
      - orders
      summary: ini fitur lihat detail order
      description: Menampilkan detail order barang
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelOrderDetail'
              example:
                orderid: 1
                created_at: 2022-09-11T12:40:00.000+0000
                data:
                - productid: 1
                  productname: white t-shirt
                  qty: 1
                  total: 500000
                code: 200
                message: get data success
        "404":
          description: Data Not Found
          content:
            application/json:
              schema:
                type: string
              example: '{"code":404,"message":"Data not found"}'
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: string
              example: '{"code":500,"message":"There is an error in internal server"}'
      security:
      - bearerAuth: []
  /orders/idorder/cancel:
    put:
      tags:
      - orders
      summary: ini fitur cancel order
      description: Menampilkan tampilan cancel order
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelOrderDetail'
              example:
                status: success
                code: 200
                message: Success cancel order
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelOrderDetail'
              example:
                status: failed
                code: 500
                message: There is an error in internal server
      security:
      - bearerAuth: []
  /orders/idorder/confirm:
    put:
      tags:
      - orders
      summary: ini fitur confirm order
      description: Menampilkan tampilan confirm order
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelOrderDetail'
              example:
                status: success
                code: 200
                message: Success confirm order
        "500":
          description: Internal server Error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ModelOrderDetail'
              example:
                status: failed
                code: 500
                message: There is an error in internal server
      security:
      - bearerAuth: []
components:
  schemas:
    ModelUser:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        address:
          type: string
        phone:
          type: string
        role:
          type: string
        token:
          type: string
        myorderhistory:
          type: array
          items:
            $ref: '#/components/schemas/ModelUser_order'
    ModelAdmin:
      type: object
      properties:
        productid:
          type: integer
          format: int32
        productname:
          type: string
        stock:
          type: integer
          format: int32
        price:
          type: string
        foto:
          type: string
        created_at:
          type: string
          format: date-time
    ModelOrder:
      type: object
      properties:
        orderid:
          type: integer
          format: int32
        productid:
          type: integer
          format: int32
        qty:
          type: integer
          format: int32
    ModelUser_order:
      type: object
      properties:
        orderid:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
        total:
          type: integer
          format: int32
    ModelOrderDetail:
      type: object
      properties:
        orderid:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
        status:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/ModelOrderDetail_data'
    ModelOrderDetail_data:
      properties:
        productid:
          type: integer
          format: int32
        productname:
          type: string
        qty:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
      example: null
  responses:
    "404":
      description: Data Not Found
      content:
        application/json:
          schema:
            type: string
          example: '{"code":404,"message":"Data not found"}'
    "500":
      description: Internal server Error
      content:
        application/json:
          schema:
            type: string
          example: '{"code":500,"message":"There is an error in internal server"}'
  securitySchemes:
    bearerAuth:
      type: http
      description: JWT Authentication
      scheme: bearer
      bearerFormat: JWT
